# These are supported funding model platforms
custom: ['bitcoin:36Huy7Lsr4qSpVp9qoMezLfddtuhi7ntpb', 'ethereum:0xa6c5f477B7474041dFb22a60779d6e39ce8b63f1', 'doge:DTUNSpfb7kvEMmXnaDvQKQQZsWkRY1GrzV', 'solana:8QYnaoA3rE3UUZFaT4BvBNomM3mLkcqAmHTMBk6HcPhK']
